// <auto-generated />
using System;
using GestionPersonnel.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionPersonnel.API.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723124623_SsoReady_RemovePasswordHash_AddStubCredentials")]
    partial class SsoReady_RemovePasswordHash_AddStubCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionPersonnel.API.Models.Conge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChefServiceId")
                        .HasColumnType("int");

                    b.Property<string>("CommentaireChef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommentaireDirecteur")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTraitementChef")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateTraitementDirecteur")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DirecteurId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChefServiceId");

                    b.HasIndex("DirecteurId");

                    b.HasIndex("EmployeId");

                    b.ToTable("Conges");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Directions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Direction des Ressources Humaines",
                            Nom = "Direction RH"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Direction Technique",
                            Nom = "Direction Technique"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Direction Informatique",
                            Nom = "Direction Informatique"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Direction du Patrimoine",
                            Nom = "Direction Patrimoine"
                        });
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.HasIndex("ResponsableId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "AdministrateurRH"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Directeur"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "ChefDeService"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Employe"
                        });
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Recrutement des talents",
                            DirectionId = 1,
                            Nom = "Service Recrutement"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Formation et développement",
                            DirectionId = 1,
                            Nom = "Service Formation"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gestion de la paie",
                            DirectionId = 1,
                            Nom = "Service Paie"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Maintenance technique",
                            DirectionId = 2,
                            Nom = "Service Maintenance"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Exploitation technique",
                            DirectionId = 2,
                            Nom = "Service Exploitation"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Développement logiciel",
                            DirectionId = 3,
                            Nom = "Service Développement"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Infrastructure IT",
                            DirectionId = 3,
                            Nom = "Service Infrastructure"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Gestion immobilière",
                            DirectionId = 4,
                            Nom = "Service Immobilier"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Logistique et achats",
                            DirectionId = 4,
                            Nom = "Service Logistique"
                        });
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.StubCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StubCredentials");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SsoId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("SsoId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Conge", b =>
                {
                    b.HasOne("GestionPersonnel.API.Models.Employe", "ChefService")
                        .WithMany()
                        .HasForeignKey("ChefServiceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestionPersonnel.API.Models.Employe", "Directeur")
                        .WithMany()
                        .HasForeignKey("DirecteurId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestionPersonnel.API.Models.Employe", "Employe")
                        .WithMany("Conges")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChefService");

                    b.Navigation("Directeur");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Employe", b =>
                {
                    b.HasOne("GestionPersonnel.API.Models.Direction", "Direction")
                        .WithMany("Employes")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPersonnel.API.Models.Employe", "Responsable")
                        .WithMany("Subordonnes")
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("GestionPersonnel.API.Models.Service", "Service")
                        .WithMany("Employes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GestionPersonnel.API.Models.User", "User")
                        .WithOne("Employe")
                        .HasForeignKey("GestionPersonnel.API.Models.Employe", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Direction");

                    b.Navigation("Responsable");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Service", b =>
                {
                    b.HasOne("GestionPersonnel.API.Models.Direction", "Direction")
                        .WithMany("Services")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.StubCredential", b =>
                {
                    b.HasOne("GestionPersonnel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.User", b =>
                {
                    b.HasOne("GestionPersonnel.API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Direction", b =>
                {
                    b.Navigation("Employes");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Employe", b =>
                {
                    b.Navigation("Conges");

                    b.Navigation("Subordonnes");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.Service", b =>
                {
                    b.Navigation("Employes");
                });

            modelBuilder.Entity("GestionPersonnel.API.Models.User", b =>
                {
                    b.Navigation("Employe");
                });
#pragma warning restore 612, 618
        }
    }
}
